spring:
  application:
    name: product-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/microservices-realm/protocol/openid-connect/certs

server:
  port: 9191
